include: config.yaml

run:
  name: ucf101-gfvd-vjepa2-1

checkpoints:
  stage1: ckpts/vrae/vrae_vjepa2.1.pt
  dit: ckpts/ucf101_dit/ucf101_dit_vjepa2.1.pt
  latent_normalizer: ckpts/ucf101_dit/ucf101_latent_stats_vjepa2.1.pt
