include: decoder_vit_xl.yaml
model:
  name: vrae
  encoder:
    name: dinov3
    variant: vit_l16
    layers: [11, 13, 15, 17, 19, 21, 23]
    fusion: mean_plus_final_spatial_mean
    hidden_size: 1024
    num_blocks: 24
    patch_size: 16
    encoder_tubelet_size: 1
    pixel_normalization: imagenet
    image_size: [256, 256]
    checkpoint: ckpts/pretrained/encoders/dinov3/model.pth
  pooling:
    name: temporal_attention
    group_size: 4
    num_heads: 16
    use_time_bias: true
    output_norm_affine: false
