include: decoder_vit_xl.yaml
model:
  name: vrae
  encoder:
    name: eupe
    variant: vit_b16
    layers: [5, 6, 7, 8, 9, 10, 11]
    fusion: sum
    hidden_size: 768
    num_blocks: 12
    patch_size: 16
    encoder_tubelet_size: 1
    pixel_normalization: imagenet
    image_size: [256, 256]
    checkpoint: ckpts/pretrained/encoders/eupe/model.pt
  pooling:
    name: temporal_attention
    group_size: 4
    num_heads: 16
    use_time_bias: true
    output_norm_affine: false

