include:
  - vjepa2_1_lerobot.yaml
run_name: vjepa2_1_libero_reconstruction_single_gpu_bs4
training:
  init_from: null
  init_weights: model
  epochs: 50
  global_batch_size: 4
  num_workers: 8
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true
  prefetch_to_device: true
  checkpoint_interval: 1000
wandb:
  mode: online
