include: config_vjepa2_1.yaml

run:
  name: ucf101-rfvd-vjepa2-1-interval1

inputs:
  population: data/metadata/ucf101_test_split1_rfvd_f16_dt1.json

evaluation:
  population_size: 3783
  frame_interval: 1
